### ISSUE TITLE
[BUG] (game breaking) Punching mobs with empty hand does nothing, generates error

### ISSUE THREAD

**Issue by TrevorBagels** [yeelp/Distinct-Damage-Descriptions#42]
Whenever I punch a zombie, or attack it with an item from another mod, nothing happens and I get this error
It also appears to happen when I attack a zombie using an axe. Attacking modded mobs works normally (without errors). I only just installed this mod, so maybe it's an issue with the config.
```
[08:24:57] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent)
[08:24:57] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: yeelp/distinctdamagedescriptions/client/render/particle/DDDParticle
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoClassDefFoundError: yeelp/distinctdamagedescriptions/client/render/particle/DDDParticle
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.doEffects(DamageHandler.java:199) ~[DamageHandler.class:?]
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.onHit(DamageHandler.java:171) ~[DamageHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) ~[ForgeHooks.class:14.23.5.2854]
	at net.minecraft.entity.EntityLivingBase.damageEntity(EntityLivingBase.java:1410) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:926) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
	at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:233) ~[adt.class:?]
	at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1328) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1425) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1092) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13) ~[li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
[08:24:58] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingHurtEvent@7eb96ed7:
java.lang.NoClassDefFoundError: yeelp/distinctdamagedescriptions/client/render/particle/DDDParticle
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.doEffects(DamageHandler.java:199) ~[DamageHandler.class:?]
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.onHit(DamageHandler.java:171) ~[DamageHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) [ForgeHooks.class:14.23.5.2854]
	at net.minecraft.entity.EntityLivingBase.damageEntity(EntityLivingBase.java:1410) [vp.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:926) [vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) [ade.class:?]
	at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:233) [adt.class:?]
	at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1328) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1425) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1092) [pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69) [li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13) [li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[08:24:58] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[08:24:58] [Server thread/ERROR] [FML]: 0: HIGHEST
[08:24:58] [Server thread/ERROR] [FML]: 1: ASM: yeelp.distinctdamagedescriptions.handlers.DamageHandler@7eca3058 onHit(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 2: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentButchering@4604850 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 3: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentDefusion@1595b223 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 4: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentSpellBreaker@35b95020 onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 5: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentWaterAspect@db286ce HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 6: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentAdvancedEfficiency@49d4c6b9 onAxeAttackEfficiency(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 7: ASM: com.Shultrea.Rin.Ench0_2_0.EnchantmentMortalitas@4123acc0 onDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 8: ASM: com.Shultrea.Rin.Ench0_2_0.EnchantmentCulling@2735044a HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 9: ASM: com.Shultrea.Rin.Ench0_2_0.EnchantmentPenetratingEdge@3e4fcc04 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 10: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentClearsky@4ed3814f HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 11: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentMoonlight@6482d8e8 onHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 12: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentSunshine@6e167b52 onHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 13: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentThunderstorm@65e97b5f HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 14: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentWinter@29e5c7f6 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 15: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentStrafe@593b2b4 onEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 16: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentPurgingBlade@b5268cc HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 17: ASM: com.Shultrea.Rin.Ench0_4_0.EnchantmentDarkShadows@bc25e2b onEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 18: ASM: com.Shultrea.Rin.Utility_Sector.OtherHandler@10893be3 enchHand(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 19: HIGH
[08:24:58] [Server thread/ERROR] [FML]: 20: ASM: class techguns.events.TGEventHandler onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 21: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentSwifterSlashes@30b5c327 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 22: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentViper@1669df74 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 23: NORMAL
[08:24:58] [Server thread/ERROR] [FML]: 24: ASM: class artifacts.common.item.BaubleStarCloak onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 25: ASM: class artifacts.common.item.BaubleMagmaStone onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 26: ASM: class artifacts.common.item.BaubleAmulet onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 27: ASM: class artifacts.common.item.BaubleObsidianSkull onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 28: ASM: class the_fireplace.clans.forge.event.LandProtectionEvents onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 29: ASM: class net.insane96mcp.progressivebosses.events.LivingHurt EventLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 30: ASM: class com.daposeidonguy.teamsmod.common.network.PacketEvents onPlayerDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 31: ASM: crafttweaker.mc1120.events.CommonEventHandler@1a007bbb onEntityLivingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 32: ASM: cofh.core.proxy.EventHandler@64b8bfbb handleLivingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 33: ASM: flaxbeard.cyberware.common.item.ItemSkinUpgrade@65a938bf handleHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 34: ASM: flaxbeard.cyberware.common.item.ItemMuscleUpgrade@78bf9c70 handleHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 35: ASM: flaxbeard.cyberware.common.item.ItemBoneUpgrade@30ac24c1 handleFallDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 36: ASM: pegbeard.dungeontactics.handlers.DTEventHandler@6260bf livingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 37: ASM: com.yyon.grapplinghook.items.LongFallBoots@302d8b99 onLivingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 38: ASM: com.yyon.grapplinghook.ServerProxyClass@2efb06b2 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 39: ASM: omtteam.openmodularturrets.handler.OMTEventHandler@5d59f2b5 entityHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 40: ASM: com.mr208.rewired.common.items.equipment.ItemARVisor@50993039 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 41: ASM: uniquee.handler.EntityEvents@5264daa9 onEntityAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 42: ASM: c4.conarm.common.armor.modifiers.ModSticky@75f8d4c4 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 43: ASM: slimeknights.tconstruct.shared.AchievementEvents@69973563 onDamageEntity(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 44: ASM: c4.conarm.common.armor.traits.TraitEnderport@558aeaf7 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 45: ASM: c4.conarm.common.armor.traits.TraitCombustible@7ed6b95b onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 46: ASM: c4.conarm.common.armor.traits.TraitBlessed@433fb6e onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 47: ASM: c4.conarm.common.armor.traits.TraitSteady@62e387df onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 48: ASM: c4.conarm.common.armor.traits.TraitVoltaic@78d1a1fe onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 49: ASM: c4.conarm.common.events.ArmorEvents@5f98589a playerHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 50: ASM: matteroverdrive.handler.EntityHandler@6f877b61 onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 51: ASM: com.lothrazar.cyclicmagic.potion.effect.PotionEnder@26dd8bb5 onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 52: ASM: CoroUtil.forge.EventHandlerForge@3ba1cb8 entityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 53: ASM: noppes.npcs.ScriptPlayerEventHandler$ForgeEventHandler@5a85ba59 forgeEntity(Lnet/minecraftforge/fml/common/eventhandler/Event;)V
[08:24:58] [Server thread/ERROR] [FML]: 54: ASM: noppes.npcs.ScriptPlayerEventHandler@437449cf invoke(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 55: ASM: flaxbeard.cyberware.common.handler.EssentialsMissingHandler@22b59ff2 handleMissingSkin(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 56: ASM: com.inventorypets.events.KnockbackAttackHandler@273029d5 notifyAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 57: ASM: com.inventorypets.events.LifeSaveAttackHandler@1b302c38 notifyAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 58: ASM: com.inventorypets.events.PufferfishAttackHandler@23743990 notifyAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 59: ASM: com.inventorypets.events.LifestealAttackHandler@2c4f8bfc notifyAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 60: ASM: com.inventorypets.events.ExplosivesAttackHandler@234b7bba notifyAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 61: ASM: com.inventorypets.events.ItemEntityEvents@88ac5e1 onEntityTakeDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 62: ASM: ca.glasspelican.loginshield.loginshield@79e1380f onLivingAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 63: ASM: slimeknights.tconstruct.tools.TraitEvents@13ed0fe8 playerBlockOrHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 64: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentBlessedEdge@7f538077 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 65: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentRaining@28f76032 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 66: ASM: com.Shultrea.Rin.Ench0_4_0.EnchantmentDisarmament@3c379875 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 67: LOW
[08:24:58] [Server thread/ERROR] [FML]: 68: ASM: class quarris.rotm.event.EntityEventHandler applyMobOffenseEffect(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 69: ASM: class quarris.rotm.event.EntityEventHandler applyMobDefenseEffect(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 70: ASM: slimeknights.tconstruct.tools.melee.item.BattleSign@6e962b38 reducedDamageBlocked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 71: ASM: com.Shultrea.Rin.Ench0_2_0.EnchantmentUnpredictable@26dfd117 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 72: ASM: com.Shultrea.Rin.Ench0_2_0.EnchantmentLifesteal@5f0fb560 HandlingFirst(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 73: ASM: com.Shultrea.Rin.Ench0_3_0.EnchantmentDesolator@4370edff HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 74: ASM: com.Shultrea.Rin.Utility_Sector.AdditionalProtectionEnchantmentsEffects@4e7e6ab4 protectionOnly(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 75: ASM: com.Shultrea.Rin.Utility_Sector.AdditionalProtectionEnchantmentsEffects@4e7e6ab4 projprotection(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 76: ASM: com.Shultrea.Rin.Utility_Sector.AdditionalProtectionEnchantmentsEffects@4e7e6ab4 blastprotection(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 77: ASM: com.Shultrea.Rin.Utility_Sector.AdditionalProtectionEnchantmentsEffects@4e7e6ab4 featherfall(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 78: LOWEST
[08:24:58] [Server thread/ERROR] [FML]: 79: ASM: flaxbeard.cyberware.common.item.ItemHeartUpgrade@78fb0ea7 handleHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 80: ASM: blusunrize.immersiveengineering.common.EventHandler@48482bf0 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 81: ASM: com.Shultrea.Rin.Ench0_2_0.EnchantmentRune_MagicalBlessing@6898d384 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 82: ASM: com.Shultrea.Rin.Ench0_1_0.EnchantmentRune_PiercingCapabilities@77aa3a90 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/ERROR] [FML]: 83: ASM: com.Shultrea.Rin.Ench0_4_5.EnchantmentMastery@39c7ad66 HandleEnchant(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[08:24:58] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent)
[08:24:58] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: yeelp/distinctdamagedescriptions/client/render/particle/DDDParticle
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoClassDefFoundError: yeelp/distinctdamagedescriptions/client/render/particle/DDDParticle
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.doEffects(DamageHandler.java:199) ~[DamageHandler.class:?]
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.onHit(DamageHandler.java:171) ~[DamageHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_DamageHandler_onHit_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) ~[ForgeHooks.class:14.23.5.2854]
	at net.minecraft.entity.EntityLivingBase.damageEntity(EntityLivingBase.java:1410) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:926) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
	at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:233) ~[adt.class:?]
	at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1328) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1425) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1092) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13) ~[li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
```
I'm on version 1.2 by the way.

**Comment by yeelp** [comment]
Man I thought I fixed this problem...

What's happening is it's trying to spawn particles because zombies, by default, have a bludgeoning resistance, and all items inflict bludgeoning damage by default. Modded mobs have no resistances by default so this is bypassed.

Is this on a dedicated server or single player?

**Comment by TrevorBagels** [comment]
It's on a dedicated server
