### ISSUE TITLE
Null pointer exception when you kill a Parrot by any means

### ISSUE THREAD

**Issue by James103** [yeelp/Distinct-Damage-Descriptions#6]
When you feed a Parrot with a Cookie, the game reports a scheduled task exception `java.lang.NullPointerException`. This does not crash the game.

<details>
<summary>Log and crash report (version info included)</summary>

```
[13:32:51] [Server thread/INFO] [distinctdamagedescriptions]: [DISTINCT DAMAGE DESCRIPTIONS (DEBUG)]Damage Type: player Attacker: player, True Attacker: null Defender: minecraft:parrot
[13:32:51] [Server thread/INFO] [distinctdamagedescriptions]: [DISTINCT DAMAGE DESCRIPTIONS (DEBUG)]Damage Categories: (slashing: 0.000000, piercing: 0.000000, bludgeoning: 340282346638528860000000000000000000000.000000)
[13:32:51] [Server thread/INFO] [distinctdamagedescriptions]: [DISTINCT DAMAGE DESCRIPTIONS (DEBUG)]starting damage: 3.4028235E38
[13:32:51] [Server thread/INFO] [distinctdamagedescriptions]: [DISTINCT DAMAGE DESCRIPTIONS (DEBUG)]Damage Total: (null, null, 3.4028235E38)
[13:32:51] [Server thread/INFO] [distinctdamagedescriptions]: [DISTINCT DAMAGE DESCRIPTIONS (DEBUG)]new damage after physical deductions: Infinity
[13:32:51] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@5986aae6:
java.lang.NullPointerException: null
	at yeelp.distinctdamagedescriptions.handlers.DamageHandler.onDeath(DamageHandler.java:70) ~[DamageHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_DamageHandler_onDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:615) [ForgeHooks.class:14.23.5.2854]
	at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1168) [vp.class:?]
	at net.minecraft.entity.passive.EntityTameable.onDeath(SourceFile:213) [wb.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023) [vp.class:?]
	at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(SourceFile:66) [zv.class:?]
	at net.minecraft.entity.passive.EntityParrot.attackEntityFrom(EntityParrot.java:426) [aac.class:?]
	at net.minecraft.entity.passive.EntityParrot.processInteract(EntityParrot.java:276) [aac.class:?]
	at net.minecraft.entity.EntityLiving.processInitialInteract(EntityLiving.java:1227) [vq.class:?]
	at net.minecraft.entity.player.EntityPlayer.interactOn(EntityPlayer.java:1199) [aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1075) [pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69) [li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13) [li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[13:32:51] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[13:32:51] [Server thread/ERROR] [FML]: 0: NORMAL
[13:32:51] [Server thread/ERROR] [FML]: 1: ASM: yeelp.distinctdamagedescriptions.handlers.DamageHandler@7e77ec04 onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[13:32:51] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_DamageHandler_onDeath_LivingDeathEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_DamageHandler_onDeath_LivingDeathEvent)
[13:32:51] [Server thread/FATAL] [VanillaFix]: Minecraft ran into a problem! Report saved to: C:\Users\james\Documents\MultiMC\instances\1.12.2 C\.minecraft\crash-reports\crash-2020-08-21_13.32.51-server.txt
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2020-08-21 13:32:51 CDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at yeelp.distinctdamagedescriptions.handlers.DamageHandler.onDeath(DamageHandler.java:70)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_DamageHandler_onDeath_LivingDeathEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:615)
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1168)
    at net.minecraft.entity.passive.EntityTameable.onDeath(SourceFile:213)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(SourceFile:66)
    at net.minecraft.entity.passive.EntityParrot.attackEntityFrom(EntityParrot.java:426)
    at net.minecraft.entity.passive.EntityParrot.processInteract(EntityParrot.java:276)
    at net.minecraft.entity.EntityLiving.processInitialInteract(EntityLiving.java:1227)
    at net.minecraft.entity.player.EntityPlayer.interactOn(EntityPlayer.java:1199)
    at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1075)
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69)
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3397715240 bytes (3240 MB) / 4747427840 bytes (4527 MB) up to 4747427840 bytes (4527 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4608m -Xmx4608m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 9 mods loaded, 9 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                         | Version         | Source                                    | Signature                                |
       |:------ |:-------------------------- |:--------------- |:----------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                  | 1.12.2          | minecraft.jar                             | None                                     |
       | LCHIJA | mcp                        | 9.42            | minecraft.jar                             | None                                     |
       | LCHIJA | FML                        | 8.0.99.99       | forge-1.12.2-14.23.5.2854-universal.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                      | 14.23.5.2854    | forge-1.12.2-14.23.5.2854-universal.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | attributefix               | 1.0.4           | AttributeFix-1.12.2-1.0.4.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | classicbar                 | @VERSION@       | classicbar-0.5.4.jar                      | None                                     |
       | LCHIJA | distinctdamagedescriptions | 1.0.0-beta      | distinctdamagedescriptions-1.0.0-beta.jar | None                                     |
       | LCHIJA | jei                        | 4.15.0.291      | jei_1.12.2-4.15.0.291.jar                 | None                                     |
       | LCHIJA | vanillafix                 | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar                  | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Distinct Damage Descriptions (distinctdamagedescriptions)

[13:32:56] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[13:32:56] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/overworld
```

</details>

Also note that Wolves and Ocelots will cause the same problems as Parrots. Additionally, they will outright crash the server if killed via enviornmental damage (including from any explosion).

Additionally, if multiple Wolves, Parrots, or Ocelots die at (or near) the same time, the game will crash and require a world reload once for every such entity death.

**Comment by yeelp** [comment]
Verified: commit 8e13ad07e21782c2fdcc41513776b85e354b01d2 fixes this
